name: 'Container Image Builder'

description: 'Builder Container Images'

inputs:

  GIT_TAG_VERSION_MAJOR_MINOR:
    description: 'Major/Minor Version of the Image to Build'
    required: true
  GITLAB_USERNAME:
    description: 'GitLab Username'
    required: true
  GITLAB_TOKEN:
    description: 'GitLab Token'
    required: true
  GCR_GITHUB_USERNAME:
    description: 'GCR GitHub Username'
    required: true
  GCR_GITHUB_TOKEN:
    description: 'GCR GitHub Token'
    required: true
  DOCKERHUB_USERNAME:
    description: 'DockerHub Username'
    required: true
  DOCKERHUB_TOKEN:
    description: 'DockerHub Token'
    required: true

runs:

  using: "composite"

  steps:

      - name: Set Environment Variables
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "DEVOPS_IMAGE_VERSION=$(echo $GIT_TAG_VERSION_MAJOR_MINOR).$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
        shell: bash

      - name: Build Information
        run: |
          echo \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
          echo BUILD INFORMATION:
          echo ------------------
          [ ! -z "$GITHUB_EVENT_NAME" ]     && echo "GitHub Event:            $GITHUB_EVENT_NAME"
          [ ! -z "$GITHUB_RUN_ID" ]         && echo "GitHub Run ID:           $GITHUB_RUN_ID"
          [ ! -z "$GITHUB_RUN_NUMBER" ]     && echo "GitHub Run No:           $GITHUB_RUN_NUMBER"
          [ ! -z "$GITHUB_SHA" ]            && echo "Commit SHA:              $GITHUB_SHA"
          [ ! -z "$SHORT_SHA" ]             && echo "Short SHA:               $SHORT_SHA"
          [ ! -z "$GITHUB_REPOSITORY" ]     && echo "Repo Name:               $GITHUB_REPOSITORY"
          [ ! -z "$GITHUB_REF" ]            && echo "Repo Ref:                $GITHUB_REF"
          [ ! -z "$GITHUB_HEAD_REF" ]       && echo "Head Branch:             $GITHUB_HEAD_REF"
          [ ! -z "$GITHUB_BASE_REF" ]       && echo "Base Branch:             $GITHUB_BASE_REF"
          [ ! -z "$RUNNER_NAME" ]           && echo "Runner Name:             $RUNNER_NAME"
          [ ! -z "$RUNNER_OS" ]             && echo "Runner OS:               $RUNNER_OS"
          [ ! -z "$DEVOPS_IMAGE_VERSION" ]  && echo "DevOps Image Version:    $DEVOPS_IMAGE_VERSION"
          echo \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ inputs.GITLAB_USERNAME }}
          password: ${{ inputs.GITLAB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.GCR_GITHUB_USERNAME }}
          password: ${{ inputs.GCR_GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ inputs.DOCKERHUB_TOKEN }}