name: Update Tool Versions

description: 'Fetch latest tool versions, update GitHub variables, and trigger image build if needed.'

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2am UTC
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (do not update variables or trigger build)'
        required: false
        default: false
        type: boolean

jobs:
  update-tool-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest GitHub CLI
        run: |
          sudo apt-get remove -y gh || true
          sudo rm -f /usr/bin/gh
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh
          gh --version

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run update_tool_versions.sh
        run: scripts/update_tool_versions.sh
        env:
          GH_TOKEN: ${{ secrets.GCR_GITHUB_TOKEN }}
          DRY_RUN: ${{ github.event.inputs.dry_run == true && '1' || '0' }}
